import React, { useCallback, useEffect, useState } from 'react';
import { getCategories } from '../../data/repository';
import { addPassportNeed, createPassportReferral, getActiveOrganizations, getCommunityPassport, grantPassportConsent, recordCommunityView } from '../../services/communityPassportRepository';

const statusLabel = (status, es) => ({ new: es ? 'Nuevo' : 'New', accepted: es ? 'Aceptado' : 'Accepted', contact_attempted: es ? 'Intento de contacto' : 'Contact attempted', contacted: es ? 'Contactado' : 'Contacted', enrolled: es ? 'Inscrito' : 'Enrolled', service_received: es ? 'Servicio recibido' : 'Service received', not_eligible: es ? 'No elegible' : 'Not eligible', unable_to_contact: es ? 'No se pudo contactar' : 'Unable to contact', closed: es ? 'Cerrado' : 'Closed' }[status] || status);

export default function CommunityPassportDetail({ id, session, lang, navigate, notify }) {
  const es = lang === 'es'; const [data, setData] = useState(null); const [categories, setCategories] = useState([]); const [organizations, setOrganizations] = useState([]); const [error, setError] = useState(''); const [showNeed, setShowNeed] = useState(false); const [showReferral, setShowReferral] = useState(false);
  const load = useCallback(() => getCommunityPassport(session.access_token, id).then(setData).catch(() => setError(es ? 'No pudimos cargar este pasaporte.' : 'We could not load this passport.')), [es, id, session.access_token]);
  useEffect(() => { load(); recordCommunityView(session.access_token, 'passport', id).catch(() => {}); getCategories().then(setCategories); getActiveOrganizations(session.access_token).then(setOrganizations).catch(() => {}); }, [id, load, session.access_token]);
  const addNeed = async event => { event.preventDefault(); const f = new FormData(event.currentTarget); try { await addPassportNeed(session.access_token, { p_passport_id: id, p_category_id: f.get('category'), p_title: f.get('title'), p_description: f.get('description') || null, p_priority: f.get('priority') }); setShowNeed(false); notify(es ? 'Necesidad añadida.' : 'Need added.'); load(); } catch { setError(es ? 'No pudimos añadir la necesidad.' : 'We could not add the need.'); } };
  const refer = async event => { event.preventDefault(); const f = new FormData(event.currentTarget); const allowed = f.getAll('shared'); try { const consent = await grantPassportConsent(session.access_token, { p_passport_id: id, p_authorized_organization_id: f.get('organization'), p_allowed_fields: allowed, p_purpose: f.get('purpose'), p_expires_at: new Date(Date.now() + 365 * 86400000).toISOString() }); await createPassportReferral(session.access_token, { p_passport_id: id, p_need_id: f.get('need'), p_consent_id: consent, p_to_organization_id: f.get('organization'), p_reason: f.get('reason'), p_priority: f.get('priority'), p_resource_id: null }); setShowReferral(false); notify(es ? 'Referido enviado.' : 'Referral sent.'); load(); } catch { setError(es ? 'No pudimos enviar el referido. Revisa el consentimiento.' : 'We could not send the referral. Check the consent.'); } };
  if (error && !data) return <section className="admin-error-state"><p>{error}</p><button onClick={load}>{es ? 'Intentar nuevamente' : 'Try again'}</button></section>;
  if (!data) return <p>{es ? 'Cargando…' : 'Loading…'}</p>;
  const person = data.person;
  return <section className="community-page"><a href="/admin/pasaportes" onClick={e => { e.preventDefault(); navigate('/admin/pasaportes'); }}>← {es ? 'Volver a pasaportes' : 'Back to passports'}</a><header className="community-detail-header"><div><h1>{person.preferred_name || [person.first_name, person.last_name].filter(Boolean).join(' ')}</h1><p>{person.preferred_language === 'es' ? 'Español' : person.preferred_language === 'en' ? 'English' : 'Other'} · {person.zip_code || 'ZIP —'}</p></div><span className="status-badge status-published">{data.passport.status === 'active' ? (es ? 'Activo' : 'Active') : (es ? 'Cerrado' : 'Closed')}</span></header>
    {error && <p className="form-error" role="alert">{error}</p>}
    <div className="community-detail-grid"><section className="community-panel"><header><h2>{es ? 'Necesidades' : 'Needs'}</h2><button className="secondary-button" onClick={() => setShowNeed(v => !v)}>+ {es ? 'Añadir' : 'Add'}</button></header>{showNeed && <form className="inline-community-form" onSubmit={addNeed}><label>{es ? 'Categoría' : 'Category'}<select name="category" required>{categories.map(cat => <option key={cat.id} value={cat.id}>{es ? cat.label_es : cat.label_en}</option>)}</select></label><label>{es ? 'Necesidad' : 'Need'}<input name="title" required/></label><label>{es ? 'Descripción breve' : 'Brief description'}<textarea name="description"/></label><label>{es ? 'Prioridad' : 'Priority'}<select name="priority"><option value="standard">{es ? 'Estándar' : 'Standard'}</option><option value="urgent">{es ? 'Urgente' : 'Urgent'}</option></select></label><button className="primary-button">{es ? 'Guardar necesidad' : 'Save need'}</button></form>}<div className="community-stack">{data.needs.map(need => <article key={need.id}><strong>{need.title}</strong><span>{need.priority === 'urgent' ? (es ? 'Urgente' : 'Urgent') : (es ? 'Estándar' : 'Standard')}</span>{need.description && <p>{need.description}</p>}</article>)}</div></section>
      <section className="community-panel"><header><h2>{es ? 'Referidos' : 'Referrals'}</h2><button className="primary-button" disabled={!data.needs.some(n => n.status === 'active')} onClick={() => setShowReferral(v => !v)}>{es ? 'Referir a organización' : 'Refer to organization'}</button></header>{showReferral && <form className="inline-community-form" onSubmit={refer}><label>{es ? 'Necesidad' : 'Need'}<select name="need">{data.needs.filter(n => n.status === 'active').map(n => <option key={n.id} value={n.id}>{n.title}</option>)}</select></label><label>{es ? 'Organización' : 'Organization'}<select name="organization">{organizations.filter(o => o.id !== data.organization.id).map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></label><fieldset><legend>{es ? 'Información autorizada' : 'Authorized information'}</legend>{[['preferred_name', es ? 'Nombre preferido' : 'Preferred name'], ['first_name', es ? 'Nombre' : 'First name'], ['last_name', es ? 'Apellido' : 'Last name'], ['phone', es ? 'Teléfono' : 'Phone'], ['email', 'Email'], ['preferred_language', es ? 'Idioma' : 'Language'], ['zip_code', 'ZIP'], ['need_summary', es ? 'Resumen de necesidad' : 'Need summary']].map(([value,label]) => <label className="checkbox-label" key={value}><input type="checkbox" name="shared" value={value} defaultChecked={['preferred_name','phone','preferred_language','zip_code','need_summary'].includes(value)}/>{label}</label>)}</fieldset><label>{es ? 'Propósito' : 'Purpose'}<input name="purpose" defaultValue={es ? 'Conectar a la persona con el servicio solicitado.' : 'Connect the participant with the requested service.'} required/></label><label>{es ? 'Razón del referido' : 'Referral reason'}<textarea name="reason" required/></label><label className="checkbox-label"><input type="checkbox" required/>{es ? 'Confirmo que la persona autorizó verbalmente compartir esta información.' : 'I confirm the participant verbally authorized sharing this information.'}</label><input type="hidden" name="priority" value="standard"/><button className="primary-button">{es ? 'Enviar referido' : 'Send referral'}</button></form>}<div className="community-stack">{data.referrals.map(ref => <article key={ref.id}><strong>{ref.to_organization.name}</strong><span className={`referral-status status-${ref.status}`}>{statusLabel(ref.status, es)}</span>{ref.completed_at && <p>{es ? 'Completado' : 'Completed'} {new Intl.DateTimeFormat(lang, { dateStyle: 'medium' }).format(new Date(ref.completed_at))}</p>}</article>)}</div></section>
      <section className="community-panel"><h2>{es ? 'Consentimientos' : 'Consent'}</h2><div className="community-stack">{data.consents.map(consent => <article key={consent.id}><strong>{consent.authorized_organization.name}</strong><span>{statusLabel(consent.status, es)}</span><p>{consent.allowed_fields.join(', ')}</p></article>)}</div></section>
      <section className="community-panel"><h2>{es ? 'Actividad' : 'Timeline'}</h2><ol className="community-timeline">{data.timeline.map(item => <li key={item.id}><strong>{statusLabel(item.update_type, es)}</strong><time>{new Intl.DateTimeFormat(lang, { dateStyle: 'medium' }).format(new Date(item.created_at))}</time>{item.note && <p>{item.note}</p>}</li>)}</ol></section>
    </div></section>;
}
