import React, { useEffect, useState } from 'react';
import { listCommunityReferrals } from '../../services/communityPassportRepository';

export default function CommunityReferralList({ session, lang, navigate }) {
  const es = lang === 'es'; const [group, setGroup] = useState('new'); const [items, setItems] = useState([]); const [state, setState] = useState('loading');
  useEffect(() => { setState('loading'); listCommunityReferrals(session.access_token, group).then(value => { setItems(value || []); setState('ready'); }).catch(() => setState('error')); }, [group, session.access_token]);
  const labels = { new: es ? 'Nuevos' : 'New', in_progress: es ? 'En proceso' : 'In progress', closed: es ? 'Cerrados' : 'Closed' };
  return <section className="community-page"><header className="admin-page-heading"><div><h1>{es ? 'Referidos' : 'Referrals'}</h1><p>{es ? 'Recibe y actualiza referidos entre organizaciones.' : 'Receive and update referrals between organizations.'}</p></div></header><div className="admin-tabs">{Object.entries(labels).map(([key,label]) => <button key={key} className={group === key ? 'is-active' : ''} onClick={() => setGroup(key)}>{label}</button>)}</div>{state === 'loading' && <p>{es ? 'Cargando…' : 'Loading…'}</p>}{state === 'error' && <p>{es ? 'No pudimos cargar los referidos.' : 'We could not load referrals.'}</p>}{state === 'ready' && items.length === 0 && <div className="admin-empty-state"><p>{es ? 'No hay referidos en esta sección.' : 'There are no referrals in this section.'}</p></div>}{items.length > 0 && <div className="community-table-wrap"><table className="community-table"><thead><tr><th>{es ? 'Persona' : 'Person'}</th><th>{es ? 'Necesidad' : 'Need'}</th><th>{es ? 'Organización de origen' : 'Originating organization'}</th><th>{es ? 'Fecha' : 'Date'}</th><th>{es ? 'Estado' : 'Status'}</th><th></th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.person_label}</strong></td><td>{item.need.title}</td><td>{item.from_organization.name}</td><td>{new Intl.DateTimeFormat(lang, { dateStyle: 'medium' }).format(new Date(item.created_at))}</td><td><span className={`referral-status status-${item.status}`}>{item.status.replaceAll('_', ' ')}</span></td><td><button className="table-link" onClick={() => navigate(`/admin/referidos/${item.id}`)}>{es ? 'Ver' : 'View'}</button></td></tr>)}</tbody></table></div>}</section>;
}
