import React, { useState } from 'react';
import { createPersonAndPassport } from '../../services/communityPassportRepository';
import { getOrganizationMemberships } from '../../services/adminPermissions';

export default function CommunityPassportCreate({ session, lang, navigate, notify }) {
  const es = lang === 'es'; const memberships = getOrganizationMemberships(session.profile); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const submit = async event => { event.preventDefault(); setSaving(true); setError(''); const data = new FormData(event.currentTarget); try { const result = await createPersonAndPassport(session.access_token, { p_organization_id: data.get('organization'), p_first_name: data.get('firstName'), p_last_name: data.get('lastName') || null, p_preferred_name: data.get('preferredName') || null, p_phone: data.get('phone') || null, p_email: data.get('email') || null, p_preferred_language: data.get('language'), p_zip_code: data.get('zip') || null }); notify(es ? 'Pasaporte creado.' : 'Passport created.'); navigate(`/admin/pasaportes/${result.passport_id}`); } catch { setError(es ? 'No pudimos crear el pasaporte. Revisa los campos.' : 'We could not create the passport. Check the fields.'); } finally { setSaving(false); } };
  return <section className="community-page community-form-page"><a href="/admin/pasaportes" onClick={e => { e.preventDefault(); navigate('/admin/pasaportes'); }}>← {es ? 'Volver a pasaportes' : 'Back to passports'}</a><h1>{es ? 'Crear pasaporte' : 'Create passport'}</h1><p>{es ? 'Guarda solo la información necesaria para coordinar ayuda.' : 'Save only the information needed to coordinate help.'}</p><form className="community-form" onSubmit={submit}>
    <fieldset><legend>{es ? 'Organización de origen' : 'Originating organization'}</legend><label>{es ? 'Organización' : 'Organization'} *<select name="organization" required>{memberships.map(item => <option key={item.organization_id} value={item.organization_id}>{item.organizations?.name || item.organization_id}</option>)}</select></label></fieldset>
    <fieldset><legend>{es ? 'Información de la persona' : 'Person information'}</legend><div className="admin-form-grid"><label>{es ? 'Nombre' : 'First name'} *<input name="firstName" required/></label><label>{es ? 'Apellido' : 'Last name'}<input name="lastName"/></label><label>{es ? 'Nombre preferido' : 'Preferred name'}<input name="preferredName"/></label><label>{es ? 'Idioma preferido' : 'Preferred language'} *<select name="language" defaultValue="es"><option value="es">Español</option><option value="en">English</option><option value="other">Other</option></select></label><label>{es ? 'Teléfono' : 'Phone'}<input name="phone" type="tel"/></label><label>Email<input name="email" type="email"/></label><label>ZIP<input name="zip" inputMode="numeric" pattern="[0-9]{5}" maxLength="5"/></label></div><p className="form-help">{es ? 'Incluye teléfono o email para poder coordinar el referido.' : 'Include a phone or email so the referral can be coordinated.'}</p></fieldset>
    {error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => navigate('/admin/pasaportes')}>{es ? 'Cancelar' : 'Cancel'}</button><button className="primary-button" disabled={saving}>{es ? 'Crear pasaporte' : 'Create passport'}</button></div>
  </form></section>;
}
